name: Get listening history

# Modified actions file
on: push
    # schedule:
    #     -   cron: "55 23 * * *"


jobs:
    Generate-Sales-Transactions:
        runs-on: ubuntu-latest 
        steps:

        -   name: checkout repo content
            uses: actions/checkout@v2
        -   name: setup python
            uses: actions/setup-python@v4
            with: 
                python-version: "3.12.5"
        
        -   name: install python packages
            run: |
                python -m pip install --upgrade pip
                pip install -r requirements.txt

        -   name: fetch api tokens
            run: |
                echo '{"CLIENT_ID": "${{ secrets.CLIENT_ID }}", "CLIENT_SECRET_KEY": "${{ secrets.CLIENT_SECRET_KEY }}", "REDIRECT_URI": "${{ secrets.REDIRECT_URI }}"}' > keys.json
                export $(cat keys.json | xargs)
                echo "REDIRECT_URI is $REDIRECT_URI"

        # -   name: Set up environment variables
        #     run: |
        #         echo "CLIENT_ID=${{ secrets.CLIENT_ID }}" >> $GITHUB_ENV
        #         echo "CLIENT_SECRET_KEY=${{ secrets.CLIENT_SECRET_KEY }}" >> $GITHUB_ENV
        #         echo "REDIRECT_URI=${{ secrets.REDIRECT_URI }}" >> $GITHUB_ENV

        -   name: generate listening history
            run: |
                python extract_recent.py

        # -   name: load data into csv
        #     run: python load_data_to_csv.py
        
        -   name: commit files
            run: |
                git config --local user.name 'AgVictorCodes'
                git config --local user.email 'victoragbeleye2@gmail.com'
                git add -A
                git commit -m "Added new json file"

        -   name: push changes
            uses: ad-m/github-push-action@v0.6.0
            with:
                github_token: ${{ secrets.GITHUB_TOKEN }}
                branch: main