name: Run data_generator.py

on: 
    schedule:
        -   cron: "0 */3 * * *"

jobs:
    Generate-Sales-Transactions:
        runs-on: ubuntu-latest 
        steps:

        -   name: checkout repo content
            uses: actions/checkout@v2
        -   name: setup python
            uses: actions/setup-python@v4
            with: 
                python-version: "3.12.5"
        
        -   name: install python packages
            run: |
                python -m pip install --upgrade pip
                pip install -r requirements.txt

        -   name: generate transactions information
            run: python data_generator.py

        -   name: load data into csv
            run: python load_data_to_csv.py
        
        -   name: commit files
            run: |
                git config --local user.name 'AgVictorCodes'
                git config --local user.email 'victoragbeleye2@gmail.com'
                git add -A
                git commit -m "Added new csv file"

        -   name: push changes
            uses: ad-m/github-push-action@v0.6.0
            with:
                github_token: ${{ secrets.GITHUB_TOKEN }}
                branch: main