name: Get Previous Listening History

on: [push]

jobs:
  Get-Previous-Weekly-Listening-History:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo Content
        uses: actions/checkout@v2

      - name: Setup Python
        uses: actions/setup-python@v4
